controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
  - name: fake_left_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_joint7
      - left_joint8
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_joint7
      - right_joint8
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: left_arm_home
  - group: right_arm
    pose: right_arm_home
  - group: left_gripper
    pose: left_gripper_close
  - group: right_gripper
    pose: right_gripper_close