arm_main:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.5
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.01
  goal_position_tolerance: 0.01
  goal_orientation_tolerance: 0.1
left:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.5
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.01
  goal_position_tolerance: 0.01
  goal_orientation_tolerance: 0.01
fake_eef:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.5
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.01
  goal_position_tolerance: 0.01
  goal_orientation_tolerance: 0.01
