arm_main_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j2
    - j3
    - j4
    - j6
    - j7
    - j8
    - tool0_joint
  gains:
    j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tool0_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j1
    - j11
  gains:
    j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
fake_eef_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - tool0_joint
  gains:
    tool0_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1